apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: modewsoft-com-tls
spec:
  secretName: modewsoft-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: modewsoft.com
  dnsNames:
    - modewsoft.com
    - www.modewsoft.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - modewsoft.com
          - www.modewsoft.com
